amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    always_reset_initial_pose: false
    base_frame_id: base_footprint
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    first_map_only: false
    global_frame_id: map
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.0
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: 0.05
    laser_model_type: likelihood_field
    map_topic: map
    max_beams: 80
    max_particles: 2000
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::DifferentialMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: false
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.5
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
bt_navigator:
  ros__parameters:
    always_reload_bt_xml: false
    default_nav_through_poses_bt_xml: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    default_nav_to_pose_bt_xml: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    filter_duration: 0.3
    global_frame: map
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    navigate_through_poses:
      plugin: nav2_bt_navigator::NavigateThroughPosesNavigator
    navigate_to_pose:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator
    navigators:
      - navigate_to_pose
      - navigate_through_poses
    path_blackboard_id: path
    robot_base_frame: base_link
    transform_tolerance: 0.5
collision_monitor:
  ros__parameters:
    FootprintApproach:
      action_type: approach
      type: polygon
      vertices:
        - - '0.3'
          - '0.2'
        - - '0.3'
          - '-0.2'
        - - '-0.3'
          - '-0.2'
        - - '-0.3'
          - '0.2'
    PolygonSlow:
      action_type: slowdown
      radius: 0.5
      type: circle
    PolygonStop:
      action_type: stop
      radius: 0.25
      type: circle
    base_frame_id: base_footprint
    cmd_vel_in_topic: cmd_vel_smoothed
    cmd_vel_out_topic: cmd_vel
    observation_sources:
      - scan
    odom_frame_id: odom
    polygons:
      - PolygonStop
      - PolygonSlow
      - FootprintApproach
    scan:
      inflation_radius: 0.6
      max_obstacle_height: 2.0
      min_obstacle_height: 0.0
      obstacle_radius: 0.5
      safety_distance: 0.2
      source: scan
      stop_distance: 0.1
      topic: /scan
      type: scan
    source_timeout: 5.0
    state_topic: collision_monitor_state
    stop_pub_timeout: 2.0
    transform_tolerance: 0.5
controller_server:
  ros__parameters:
    FollowPath:
      BaseObstacle.scale: 0.02
      GoalAlign.scale: 24.0
      GoalDist.scale: 24.0
      PathAlign.scale: 32.0
      PathDist.scale: 32.0
      RotateToGoal.lookahead_time: -1.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      angular_granularity: 0.025
      critics:
        - RotateToGoal
        - Oscillation
        - BaseObstacle
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist
      debug_trajectory_details: true
      linear_granularity: 0.05
      max_vel_theta: 1.0
      max_vel_x: 0.6
      min_vel_x: 0.1
      plugin: dwb_core::DWBLocalPlanner
      short_circuit_trajectory_evaluation: true
      sim_time: 1.0
      stateful: true
      trans_stopped_velocity: 0.25
      transform_tolerance: 1.0
      vtheta_samples: 40
      vx_samples: 20
      xy_goal_tolerance: 0.05
    controller_frequency: 10.0
    controller_plugins:
      - FollowPath
    enable_stamped_cmd_vel: true
    failure_tolerance: 0.3
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    goal_checker_plugins:
      - goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.1
    progress_checker_plugins:
      - progress_checker
global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      inflation_layer:
        cost_scaling_factor: 5.0
        inflation_radius: 0.5
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          raytrace_max_range: 3.0
          topic: /scan
      plugins:
        - static_layer
        - obstacle_layer
        - voxel_layer
        - inflation_layer
      publish_frequency: 3.0
      resolution: 0.05
      robot_base_frame: base_link
      robot_radius: 0.15
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      track_unknown_space: true
      transform_tolerance: 0.5
      update_frequency: 3.0
      voxel_layer:
        enabled: true
        mark_threshold: 0
        max_obstacle_height: 2.0
        observation_sources: scan
        origin_z: 0.0
        plugin: nav2_costmap_2d::VoxelLayer
        publish_voxel_map: true
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          topic: /scan
        z_resolution: 0.05
        z_voxels: 16
local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: odom
      height: 4
      inflation_layer:
        cost_scaling_factor: 5.0
        inflation_radius: 0.5
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          topic: /scan
      plugins:
        - obstacle_layer
        - voxel_layer
        - inflation_layer
      publish_frequency: 10.0
      resolution: 0.03
      robot_base_frame: base_link
      robot_radius: 0.15
      rolling_window: true
      update_frequency: 10.0
      voxel_layer:
        enabled: true
        mark_threshold: 0
        max_obstacle_height: 2.0
        observation_sources: scan
        origin_z: 0.0
        plugin: nav2_costmap_2d::VoxelLayer
        publish_voxel_map: true
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          raytrace_max_range: 3.0
          topic: /scan
        z_resolution: 0.05
        z_voxels: 16
      width: 4
